package org.cch.mall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.cch.mall.db.domain.MallRole;
import org.cch.mall.db.domain.MallRoleExample;

public interface MallRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_role
     *
     * @mbg.generated
     */
    long countByExample(MallRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_role
     *
     * @mbg.generated
     */
    int deleteByExample(MallRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_role
     *
     * @mbg.generated
     */
    int insert(MallRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_role
     *
     * @mbg.generated
     */
    int insertSelective(MallRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_role
     *
     * @mbg.generated
     */
    MallRole selectOneByExample(MallRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_role
     *
     * @mbg.generated
     */
    MallRole selectOneByExampleSelective(@Param("example") MallRoleExample example, @Param("selective") MallRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_role
     *
     * @mbg.generated
     */
    List<MallRole> selectByExampleSelective(@Param("example") MallRoleExample example, @Param("selective") MallRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_role
     *
     * @mbg.generated
     */
    List<MallRole> selectByExample(MallRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_role
     *
     * @mbg.generated
     */
    MallRole selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") MallRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_role
     *
     * @mbg.generated
     */
    MallRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_role
     *
     * @mbg.generated
     */
    MallRole selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_role
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MallRole record, @Param("example") MallRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_role
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MallRole record, @Param("example") MallRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MallRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MallRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_role
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") MallRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_role
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}