package org.cch.mall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.cch.mall.db.domain.MallNoticeAdmin;
import org.cch.mall.db.domain.MallNoticeAdminExample;

public interface MallNoticeAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_notice_admin
     *
     * @mbg.generated
     */
    long countByExample(MallNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_notice_admin
     *
     * @mbg.generated
     */
    int deleteByExample(MallNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_notice_admin
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_notice_admin
     *
     * @mbg.generated
     */
    int insert(MallNoticeAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_notice_admin
     *
     * @mbg.generated
     */
    int insertSelective(MallNoticeAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_notice_admin
     *
     * @mbg.generated
     */
    MallNoticeAdmin selectOneByExample(MallNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_notice_admin
     *
     * @mbg.generated
     */
    MallNoticeAdmin selectOneByExampleSelective(@Param("example") MallNoticeAdminExample example, @Param("selective") MallNoticeAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_notice_admin
     *
     * @mbg.generated
     */
    List<MallNoticeAdmin> selectByExampleSelective(@Param("example") MallNoticeAdminExample example, @Param("selective") MallNoticeAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_notice_admin
     *
     * @mbg.generated
     */
    List<MallNoticeAdmin> selectByExample(MallNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_notice_admin
     *
     * @mbg.generated
     */
    MallNoticeAdmin selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") MallNoticeAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_notice_admin
     *
     * @mbg.generated
     */
    MallNoticeAdmin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_notice_admin
     *
     * @mbg.generated
     */
    MallNoticeAdmin selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_notice_admin
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MallNoticeAdmin record, @Param("example") MallNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_notice_admin
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MallNoticeAdmin record, @Param("example") MallNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_notice_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MallNoticeAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_notice_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MallNoticeAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_notice_admin
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") MallNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_notice_admin
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}