package org.cch.mall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.cch.mall.db.domain.MallNotice;
import org.cch.mall.db.domain.MallNoticeExample;

public interface MallNoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_notice
     *
     * @mbg.generated
     */
    long countByExample(MallNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_notice
     *
     * @mbg.generated
     */
    int deleteByExample(MallNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_notice
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_notice
     *
     * @mbg.generated
     */
    int insert(MallNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_notice
     *
     * @mbg.generated
     */
    int insertSelective(MallNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_notice
     *
     * @mbg.generated
     */
    MallNotice selectOneByExample(MallNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_notice
     *
     * @mbg.generated
     */
    MallNotice selectOneByExampleSelective(@Param("example") MallNoticeExample example, @Param("selective") MallNotice.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_notice
     *
     * @mbg.generated
     */
    List<MallNotice> selectByExampleSelective(@Param("example") MallNoticeExample example, @Param("selective") MallNotice.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_notice
     *
     * @mbg.generated
     */
    List<MallNotice> selectByExample(MallNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_notice
     *
     * @mbg.generated
     */
    MallNotice selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") MallNotice.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_notice
     *
     * @mbg.generated
     */
    MallNotice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_notice
     *
     * @mbg.generated
     */
    MallNotice selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_notice
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MallNotice record, @Param("example") MallNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_notice
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MallNotice record, @Param("example") MallNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_notice
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MallNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_notice
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MallNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_notice
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") MallNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_notice
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}