package org.cch.mall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.cch.mall.db.domain.MallAftersale;
import org.cch.mall.db.domain.MallAftersaleExample;

public interface MallAftersaleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_aftersale
     *
     * @mbg.generated
     */
    long countByExample(MallAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_aftersale
     *
     * @mbg.generated
     */
    int deleteByExample(MallAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_aftersale
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_aftersale
     *
     * @mbg.generated
     */
    int insert(MallAftersale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_aftersale
     *
     * @mbg.generated
     */
    int insertSelective(MallAftersale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_aftersale
     *
     * @mbg.generated
     */
    MallAftersale selectOneByExample(MallAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_aftersale
     *
     * @mbg.generated
     */
    MallAftersale selectOneByExampleSelective(@Param("example") MallAftersaleExample example, @Param("selective") MallAftersale.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_aftersale
     *
     * @mbg.generated
     */
    List<MallAftersale> selectByExampleSelective(@Param("example") MallAftersaleExample example, @Param("selective") MallAftersale.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_aftersale
     *
     * @mbg.generated
     */
    List<MallAftersale> selectByExample(MallAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_aftersale
     *
     * @mbg.generated
     */
    MallAftersale selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") MallAftersale.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_aftersale
     *
     * @mbg.generated
     */
    MallAftersale selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_aftersale
     *
     * @mbg.generated
     */
    MallAftersale selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_aftersale
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MallAftersale record, @Param("example") MallAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_aftersale
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MallAftersale record, @Param("example") MallAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_aftersale
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MallAftersale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_aftersale
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MallAftersale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_aftersale
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") MallAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_aftersale
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}