package org.cch.mall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.cch.mall.db.domain.MallGoodsAttribute;
import org.cch.mall.db.domain.MallGoodsAttributeExample;

public interface MallGoodsAttributeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_attribute
     *
     * @mbg.generated
     */
    long countByExample(MallGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_attribute
     *
     * @mbg.generated
     */
    int deleteByExample(MallGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_attribute
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_attribute
     *
     * @mbg.generated
     */
    int insert(MallGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_attribute
     *
     * @mbg.generated
     */
    int insertSelective(MallGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_attribute
     *
     * @mbg.generated
     */
    MallGoodsAttribute selectOneByExample(MallGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_attribute
     *
     * @mbg.generated
     */
    MallGoodsAttribute selectOneByExampleSelective(@Param("example") MallGoodsAttributeExample example, @Param("selective") MallGoodsAttribute.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_attribute
     *
     * @mbg.generated
     */
    List<MallGoodsAttribute> selectByExampleSelective(@Param("example") MallGoodsAttributeExample example, @Param("selective") MallGoodsAttribute.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_attribute
     *
     * @mbg.generated
     */
    List<MallGoodsAttribute> selectByExample(MallGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_attribute
     *
     * @mbg.generated
     */
    MallGoodsAttribute selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") MallGoodsAttribute.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_attribute
     *
     * @mbg.generated
     */
    MallGoodsAttribute selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_attribute
     *
     * @mbg.generated
     */
    MallGoodsAttribute selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_attribute
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MallGoodsAttribute record, @Param("example") MallGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_attribute
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MallGoodsAttribute record, @Param("example") MallGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_attribute
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MallGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_attribute
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MallGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_attribute
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") MallGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_attribute
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}