package org.cch.mall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.cch.mall.db.domain.MallLog;
import org.cch.mall.db.domain.MallLogExample;

public interface MallLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_log
     *
     * @mbg.generated
     */
    long countByExample(MallLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_log
     *
     * @mbg.generated
     */
    int deleteByExample(MallLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_log
     *
     * @mbg.generated
     */
    int insert(MallLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_log
     *
     * @mbg.generated
     */
    int insertSelective(MallLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_log
     *
     * @mbg.generated
     */
    MallLog selectOneByExample(MallLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_log
     *
     * @mbg.generated
     */
    MallLog selectOneByExampleSelective(@Param("example") MallLogExample example, @Param("selective") MallLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_log
     *
     * @mbg.generated
     */
    List<MallLog> selectByExampleSelective(@Param("example") MallLogExample example, @Param("selective") MallLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_log
     *
     * @mbg.generated
     */
    List<MallLog> selectByExample(MallLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_log
     *
     * @mbg.generated
     */
    MallLog selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") MallLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_log
     *
     * @mbg.generated
     */
    MallLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_log
     *
     * @mbg.generated
     */
    MallLog selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MallLog record, @Param("example") MallLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MallLog record, @Param("example") MallLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MallLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MallLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_log
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") MallLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_log
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}