package org.cch.mall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.cch.mall.db.domain.MallOrderGoods;
import org.cch.mall.db.domain.MallOrderGoodsExample;

public interface MallOrderGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order_goods
     *
     * @mbg.generated
     */
    long countByExample(MallOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order_goods
     *
     * @mbg.generated
     */
    int deleteByExample(MallOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order_goods
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order_goods
     *
     * @mbg.generated
     */
    int insert(MallOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order_goods
     *
     * @mbg.generated
     */
    int insertSelective(MallOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order_goods
     *
     * @mbg.generated
     */
    MallOrderGoods selectOneByExample(MallOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order_goods
     *
     * @mbg.generated
     */
    MallOrderGoods selectOneByExampleSelective(@Param("example") MallOrderGoodsExample example, @Param("selective") MallOrderGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order_goods
     *
     * @mbg.generated
     */
    List<MallOrderGoods> selectByExampleSelective(@Param("example") MallOrderGoodsExample example, @Param("selective") MallOrderGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order_goods
     *
     * @mbg.generated
     */
    List<MallOrderGoods> selectByExample(MallOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order_goods
     *
     * @mbg.generated
     */
    MallOrderGoods selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") MallOrderGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order_goods
     *
     * @mbg.generated
     */
    MallOrderGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order_goods
     *
     * @mbg.generated
     */
    MallOrderGoods selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order_goods
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MallOrderGoods record, @Param("example") MallOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order_goods
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MallOrderGoods record, @Param("example") MallOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MallOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MallOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order_goods
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") MallOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order_goods
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}